
environment:
  AUTH_ACCESS_TOKEN: ${AUTH_ACCESS_TOKEN}
  PGHOST: ${PGHOST}
  PGUSER: ${PGUSER}
  PGPASSWORD: ${PGPASSWORD}
  PGDATABASE: ${PGDATABASE}
  PGPORT: "${PGPORT}"
  PG_DATABASE_CA_CERT: "${PG_DATABASE_CA_CERT}"
  SENTRY_DSN: "${SENTRY_DSN}"
  MAX_CONCURRENT_SAME_HOST_REQUESTS: "${MAX_CONCURRENT_SAME_HOST_REQUESTS}"
packages:
  - name: default
    actions:
      - name: request
        runtime: 'nodejs:default'
        limits:
          timeout: 5000
          memory: 128
      - name: project-status
        runtime: 'nodejs:default'
        limits:
          timeout: 5000
          memory: 128
      - name: scale
        runtime: 'nodejs:default'
        limits:
          timeout: 5000
          memory: 128
        environment:
          DO_API_TOKEN: "${DO_API_TOKEN}"
