
environment:
  AUTH_ACCESS_TOKEN: ${AUTH_ACCESS_TOKEN}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_USER: ${DATABASE_USER}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_NAME: ${DATABASE_NAME}
  SENTRY_DSN: "${SENTRY_DSN}"
  MAX_CONCURRENT_SAME_HOST_REQUESTS: "${MAX_CONCURRENT_SAME_HOST_REQUESTS}"
packages:
  - name: api
    actions:
      - name: request
        runtime: 'nodejs:default'
        limits:
          timeout: 15000
          memory: 128
      - name: project-status
        runtime: 'nodejs:default'
        limits:
          timeout: 15000
          memory: 128
      - name: scale
        runtime: 'nodejs:default'
        limits:
          timeout: 5000
          memory: 128
        environment:
          DO_API_TOKEN: "${DO_API_TOKEN}"
          TOOL_SERVICE_APP_ID: "${TOOL_SERVICE_APP_ID}"
      - name: metas
        runtime: 'nodejs:default'
        limits:
          timeout: 10000
          memory: 128
      - name: cleanup-requests
        runtime: 'nodejs:default'
        limits:
          timeout: 15000
          memory: 128

